name: Publish to PyPI and GitHub Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Generate Changelog
        id: changelog
        run: |
          {
            echo "CHANGELOG<<EOF"
            echo "## Changelog"
            echo ""
            PREVIOUS_TAG=$(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 --max-count=1) 2>/dev/null || echo "")
            if [ -n "$PREVIOUS_TAG" ]; then
              git log $PREVIOUS_TAG..HEAD --pretty=format:"- %s"
            else
              git log --pretty=format:"- %s"
            fi
            echo ""
            echo "EOF"
          } >> "$GITHUB_ENV"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ env.CHANGELOG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update CHANGELOG.md
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          echo "## ${{ github.ref_name }} ($(date +'%Y-%m-%d'))" >> CHANGELOG.md

          PREVIOUS_TAG=$(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 --max-count=1) 2>/dev/null || echo "")
          if [ -n "$PREVIOUS_TAG" ]; then
            git log $PREVIOUS_TAG..HEAD --pretty=format:"- %s" >> CHANGELOG.md
          else
            git log --pretty=format:"- %s" >> CHANGELOG.md
          fi

          git add CHANGELOG.md
          git commit -m "Update CHANGELOG for ${{ github.ref_name }}"
          git push origin HEAD:main

